use analytics;

start transaction;

ALTER TABLE `tmp_clients` ADD `arch` VARCHAR(10) NULL DEFAULT NULL AFTER `status`, ADD `mem` INT UNSIGNED NULL DEFAULT NULL AFTER `arch`, ADD `vga` VARCHAR(80) NULL DEFAULT NULL AFTER `mem`, ADD `cpu` VARCHAR(80) NULL DEFAULT NULL AFTER `vga`, ADD `ncpu` TINYINT UNSIGNED NULL DEFAULT NULL AFTER `cpu`;

ALTER TABLE `Client_Versions` ADD `arch` VARCHAR(10) NULL DEFAULT NULL AFTER `string_flavour`, ADD `mem` INT UNSIGNED NULL DEFAULT NULL AFTER `arch`, ADD `vga` VARCHAR(80) NULL DEFAULT NULL AFTER `mem`, ADD `cpu` VARCHAR(80) NULL DEFAULT NULL AFTER `vga`, ADD `ncpu` TINYINT UNSIGNED NULL DEFAULT NULL AFTER `cpu`;

ALTER TABLE `PackagesWhitelist` ADD `status` BOOLEAN NULL DEFAULT NULL AFTER `name`;

commit;