function drawChart(g,f,b,d){var c=.95*$("#"+b).parent().width();f={title:f,width:c,height:20*d,fontSize:10,legend:"none",hAxis:{viewWindow:{min:0}},chartArea:{left:"10%",right:"5%",top:"50",width:"100%",height:"100%"},backgroundColor:"transparent"};g=new google.visualization.DataView(g);g.setColumns([0,1,{calc:"stringify",sourceColumn:1,type:"string",role:"annotation"}]);b=new google.visualization.BarChart(document.getElementById(b));google.visualization.events.addListener(b,"ready",ready_charts);
b.draw(g,f)}function get_sizes(g){g=.95*$("#"+g).parent().width();$(window).height();return{width:g,height:"auto"}}
function build_data_per_month_releases(g,f){var b=[];for(i=0;12>i;i++)if(b[i]={15:0,16:0,19:0,all:0},g[i]){for(rel in g[i]){if("15"==rel)for(fla in g[i][rel])b[i][rel]+=g[i][rel][fla];if("16"==rel)for(fla in g[i][rel])b[i][rel]+=g[i][rel][fla];if("19"==rel)for(fla in g[i][rel])b[i][rel]+=g[i][rel][fla]}b[i].all=b[i]["15"]+b[i]["16"]+b[i]["19"]}var d=[],c=new Date,e=new google.visualization.DataTable;e.addColumn({type:"date",role:"domain"},"Release");e.addColumn("number","Total Release 15");e.addColumn({type:"string",
role:"style"},"Style Release 15");e.addColumn("number","Total Release 16");e.addColumn({type:"string",role:"style"},"Style Release 16");e.addColumn("number","Total Release 19");e.addColumn({type:"string",role:"style"},"Style Release 19");e.addColumn("number","Total ALL Releases");e.addColumn({type:"string",role:"style"},"Style ALL Releases");date_values=[];for(i=1;12>=i;i++)month=c.getMonth(),year=c.getFullYear(),date_to_add=new Date(year,month),d.push(date_to_add),date_values.push([date_to_add,b[i-
1]["15"],"color:blue",b[i-1]["16"],"color:red",b[i-1]["19"],"color:green",b[i-1].all,"color:grey"]),c.setMonth(month-1);e.addRows(date_values);return{data:e,options:{title:f,curveType:"function",isStacked:!1,hAxis:{title:"Months",ticks:d,format:"MMM"},vAxis:{title:"Num instances",viewWindow:{min:0},format:"#"},legend:{textStyle:{fontSize:10}},chartArea:{left:"5%",right:"10%"},focusTarget:"category",colors:["blue","red","green","grey"],lineWidth:5,tooltip:{textStyle:{fontSize:10}},backgroundColor:"transparent"}}}
function build_data_per_month_flavours(g,f){var b=[];for(i=0;12>i;i++)if(b[i]={server:0,client:0,desktop:0,other:0,all:0},g[i])for(rel in g[i])for(fla in g[i][rel])b[i][fla]+=g[i][rel][fla],b[i].all+=g[i][rel][fla];var d=[],c=new Date,e=new google.visualization.DataTable;e.addColumn({type:"date",role:"domain"},"Flavour");e.addColumn("number","Total Server");e.addColumn({type:"string",role:"style"},"Style Server");e.addColumn("number","Total Client");e.addColumn({type:"string",role:"style"},"Style Client");
e.addColumn("number","Total Desktop");e.addColumn({type:"string",role:"style"},"Style Desktop");e.addColumn("number","Total Other");e.addColumn({type:"string",role:"style"},"Style Other");e.addColumn("number","Total ALL Flavours");e.addColumn({type:"string",role:"style"},"Style Total ALL Flavours");date_values=[];for(i=1;12>=i;i++)month=c.getMonth(),year=c.getFullYear(),date_to_add=new Date(year,month),d.push(date_to_add),date_values.push([date_to_add,b[i-1].server,"color:purple",b[i-1].client,"color:teal",
b[i-1].desktop,"color:gold",b[i-1].other,"color:olive",b[i-1].all,"color:grey"]),c.setMonth(month-1);e.addRows(date_values);return{data:e,options:{title:f,curveType:"function",isStacked:!1,hAxis:{title:"Months",ticks:d,format:"MMM"},vAxis:{title:"Num instances",viewWindow:{min:0},format:"#"},legend:{textStyle:{fontSize:10}},chartArea:{left:"5%",right:"10%"},focusTarget:"category",colors:["purple","teal","gold","olive","grey"],lineWidth:5,tooltip:{textStyle:{fontSize:10}},backgroundColor:"transparent"}}}
function build_data_per_month_arch(g,f){for(var b=[],d=0;12>d;d++)if(b[d]={i686:0,x86_64:0,unkn:0},g[d])for(var c in g[d])for(var e in g[d][c])for(var a in g[d][c][e])b[d][a]+=g[d][c][e][a];c=[];e=new Date;a=new google.visualization.DataTable;a.addColumn({type:"date",role:"domain"},"Date");a.addColumn("number","Total x86");a.addColumn({type:"string",role:"style"},"Style x86");a.addColumn("number","Total x86_64");a.addColumn({type:"string",role:"style"},"Style x86_64");a.addColumn("number","Total unknown");
a.addColumn({type:"string",role:"style"},"Style unknown");date_values=[];for(d=1;12>=d;d++)month=e.getMonth(),year=e.getFullYear(),date_to_add=new Date(year,month),c.push(date_to_add),date_values.push([date_to_add,b[d-1].i686,"color:purple",b[d-1].x86_64,"color:gold",b[d-1].unkn,"color:grey"]),e.setMonth(month-1);a.addRows(date_values);return{data:a,options:{title:f,curveType:"function",isStacked:!1,hAxis:{title:"Months",ticks:c,format:"MMM"},vAxis:{title:"Num instances",viewWindow:{min:0},format:"#"},
legend:{textStyle:{fontSize:10}},chartArea:{left:"5%",right:"10%"},focusTarget:"category",colors:["purple","gold","grey"],lineWidth:5,tooltip:{textStyle:{fontSize:10}},backgroundColor:"transparent"}}}
function build_data_per_month_release_arch(g,f){for(var b=[],d=0;12>d;d++)if(b[d]={"15_i686":0,"15_x86_64":0,"15_unkn":0,"16_i686":0,"16_x86_64":0,"16_unkn":0,"19_i686":0,"19_x86_64":0,"19_unkn":0},g[d])for(var c in g[d])for(var e in g[d][c])for(var a in g[d][c][e])b[d][c+"_"+a]+=g[d][c][e][a];c=[];e=new Date;a=new google.visualization.DataTable;a.addColumn({type:"date",role:"domain"},"Date");a.addColumn("number","Total 15 x86");a.addColumn({type:"string",role:"style"},"Style 15 x86");a.addColumn("number",
"Total 15 x86_64");a.addColumn({type:"string",role:"style"},"Style 15 x86_64");a.addColumn("number","Total 15 unknown");a.addColumn({type:"string",role:"style"},"Style 15 unknown");a.addColumn("number","Total 16 x86");a.addColumn({type:"string",role:"style"},"Style 16 x86");a.addColumn("number","Total 16 x86_64");a.addColumn({type:"string",role:"style"},"Style 16 x86_64");a.addColumn("number","Total 16 unkown");a.addColumn({type:"string",role:"style"},"Style 16 unknown");a.addColumn("number","Total 19 x86");
a.addColumn({type:"string",role:"style"},"Style 19 x86");a.addColumn("number","Total 19 x86_64");a.addColumn({type:"string",role:"style"},"Style 19 x86_64");a.addColumn("number","Total 19 unkown");a.addColumn({type:"string",role:"style"},"Style 19 unknown");date_values=[];for(d=1;12>=d;d++)month=e.getMonth(),year=e.getFullYear(),date_to_add=new Date(year,month),c.push(date_to_add),date_values.push([date_to_add,b[d-1]["15_i686"],"color:purple",b[d-1]["15_x86_64"],"color:gold",b[d-1]["15_unkn"],"color:grey",
b[d-1]["16_i686"],"color:teal",b[d-1]["16_x86_64"],"color:olive",b[d-1]["16_unkn"],"color:darkgrey",b[d-1]["19_i686"],"color:orange",b[d-1]["19_x86_64"],"color:tomato",b[d-1]["19_unkn"],"color:lightsalmon"]),e.setMonth(month-1);a.addRows(date_values);return{data:a,options:{title:f,curveType:"function",isStacked:!1,hAxis:{title:"Months",ticks:c,format:"MMM"},vAxis:{title:"Num instances",viewWindow:{min:0},format:"#"},legend:{textStyle:{fontSize:10}},chartArea:{left:"5%",right:"10%"},focusTarget:"category",
colors:"purple gold grey teal olive darkgrey orange tomato lightsalmon".split(" "),lineWidth:5,tooltip:{textStyle:{fontSize:10}},backgroundColor:"transparent"}}}
function build_data_per_month_flavour_arch(g,f){for(var b=[],d=0;12>d;d++)if(b[d]={client_i686:0,client_x86_64:0,client_unkn:0,server_i686:0,server_x86_64:0,server_unkn:0,desktop_i686:0,desktop_x86_64:0,desktop_unkn:0,other_i686:0,other_x86_64:0,other_unkn:0},g[d])for(var c in g[d])for(var e in g[d][c])for(var a in g[d][c][e])b[d][e+"_"+a]+=g[d][c][e][a];c=[];e=new Date;a=new google.visualization.DataTable;a.addColumn({type:"date",role:"domain"},"Date");a.addColumn("number","Total client x86");a.addColumn({type:"string",
role:"style"},"Style client x86");a.addColumn("number","Total client x86_64");a.addColumn({type:"string",role:"style"},"Style client x86_64");a.addColumn("number","Total client unknown");a.addColumn({type:"string",role:"style"},"Style client unknown");a.addColumn("number","Total server x86");a.addColumn({type:"string",role:"style"},"Style server x86");a.addColumn("number","Total server x86_64");a.addColumn({type:"string",role:"style"},"Style server x86_64");a.addColumn("number","Total server unknown");
a.addColumn({type:"string",role:"style"},"Style server unknown");a.addColumn("number","Total desktop x86");a.addColumn({type:"string",role:"style"},"Style desktop x86");a.addColumn("number","Total desktop x86_64");a.addColumn({type:"string",role:"style"},"Style desktop x86_64");a.addColumn("number","Total desktop unknown");a.addColumn({type:"string",role:"style"},"Style desktop unknown");a.addColumn("number","Total other x86");a.addColumn({type:"string",role:"style"},"Style other x86");a.addColumn("number",
"Total other x86_64");a.addColumn({type:"string",role:"style"},"Style other x86_64");a.addColumn("number","Total other unknown");a.addColumn({type:"string",role:"style"},"Style other unknown");date_values=[];for(d=1;12>=d;d++)month=e.getMonth(),year=e.getFullYear(),date_to_add=new Date(year,month),c.push(date_to_add),date_values.push([date_to_add,b[d-1].client_i686,"color:goldenrod",b[d-1].client_x86_64,"color:gold",b[d-1].client_unkn,"color:lightgrey",b[d-1].server_i686,"color:darkviolet",b[d-1].server_x86_64,
"color:deeppink",b[d-1].server_unkn,"color:grey",b[d-1].desktop_i686,"color:slateblue",b[d-1].desktop_x86_64,"color:skyblue",b[d-1].desktop_unkn,"color:darkgrey",b[d-1].other_i686,"color:plum",b[d-1].other_x86_64,"color:pink",b[d-1].other_unkn,"color:black"]),e.setMonth(month-1);a.addRows(date_values);return{data:a,options:{title:f,curveType:"function",isStacked:!1,hAxis:{title:"Months",ticks:c,format:"MMM"},vAxis:{title:"Num instances",viewWindow:{min:0},format:"#"},legend:{textStyle:{fontSize:10}},
chartArea:{left:"5%",right:"10%"},focusTarget:"category",colors:"goldenrod gold lightgrey darkviolet deeppink grey slateblue skyblue darkgrey plum pink black".split(" "),lineWidth:5,tooltip:{textStyle:{fontSize:9}},backgroundColor:"transparent"}}}
function build_data_per_month_releases_mem(g,f){for(var b=[],d=["unkn","2G","4G","8G"],c=0;12>c;c++){b[c]={"15_2G":0,"15_4G":0,"15_8G":0,"15_unkn":0,"16_2G":0,"16_4G":0,"16_8G":0,"16_unkn":0,"19_2G":0,"19_4G":0,"19_8G":0,"19_unkn":0};for(var e in d)if(g[d[e]][c])for(var a in g[d[e]][c])for(var h in g[d[e]][c][a])b[c][a+"_"+d[e]]+=g[d[e]][c][a][h]}d=[];e=new Date;a=new google.visualization.DataTable;a.addColumn({type:"date",role:"domain"},"Date");a.addColumn("number","Total 15 < 2G");a.addColumn({type:"string",
role:"style"},"Style 15 < 2G");a.addColumn("number","Total 15 < 4G");a.addColumn({type:"string",role:"style"},"Style 15 < 4G");a.addColumn("number","Total 15 > 4G");a.addColumn({type:"string",role:"style"},"Style 15 > 4G");a.addColumn("number","Total 15 unknown");a.addColumn({type:"string",role:"style"},"Style 15 unknown");a.addColumn("number","Total 16 < 2G");a.addColumn({type:"string",role:"style"},"Style 16 < 2G");a.addColumn("number","Total 16 < 4G");a.addColumn({type:"string",role:"style"},"Style 16 < 4G");
a.addColumn("number","Total 16 > 4G");a.addColumn({type:"string",role:"style"},"Style 16 > 4G");a.addColumn("number","Total 16 unknown");a.addColumn({type:"string",role:"style"},"Style 16 unknown");a.addColumn("number","Total 19 < 2G");a.addColumn({type:"string",role:"style"},"Style 19 < 2G");a.addColumn("number","Total 19 < 4G");a.addColumn({type:"string",role:"style"},"Style 19 < 4G");a.addColumn("number","Total 19 > 4G");a.addColumn({type:"string",role:"style"},"Style 19 > 4G");a.addColumn("number",
"Total 19 unknown");a.addColumn({type:"string",role:"style"},"Style 19 unknown");date_values=[];for(c=1;12>=c;c++)month=e.getMonth(),year=e.getFullYear(),date_to_add=new Date(year,month),d.push(date_to_add),date_values.push([date_to_add,b[c-1]["15_2G"],"color:darkgoldenrod",b[c-1]["15_4G"],"color:goldenrod",b[c-1]["15_8G"],"color:gold",b[c-1]["15_unkn"],"color:lightgrey",b[c-1]["16_2G"],"color:darkviolet",b[c-1]["16_4G"],"color:deeppink",b[c-1]["16_8G"],"color:pink",b[c-1]["16_unkn"],"color:darkgrey",
b[c-1]["19_2G"],"color:palegreen",b[c-1]["19_4G"],"color:springgreen",b[c-1]["19_8G"],"color:green",b[c-1]["19_unkn"],"color:darkseagreen"]),e.setMonth(month-1);a.addRows(date_values);return{data:a,options:{title:f,curveType:"function",isStacked:!1,hAxis:{title:"Months",ticks:d,format:"MMM"},vAxis:{title:"Num instances",viewWindow:{min:0},format:"#"},legend:{textStyle:{fontSize:10}},chartArea:{left:"5%",right:"10%"},focusTarget:"category",colors:"darkgoldenrod goldenrod gold lightgrey darkviolet deeppink pink darkgrey palegreen springgreen green darkseagreen".split(" "),
lineWidth:5,tooltip:{textStyle:{fontSize:10}},backgroundColor:"transparent"}}}
function build_data_per_month_mem(g,f){for(var b=[],d=["unkn","2G","4G","8G"],c=0;12>c;c++){b[c]={unkn:0,"2G":0,"4G":0,"8G":0};for(var e in d)if(g[d[e]][c])for(var a in g[d[e]][c])for(var h in g[d[e]][c][a])b[c][d[e]]+=g[d[e]][c][a][h]}d=[];e=new Date;a=new google.visualization.DataTable;a.addColumn({type:"date",role:"domain"},"Date");a.addColumn("number","Total < 2G");a.addColumn({type:"string",role:"style"},"Style < 2G");a.addColumn("number","Total < 4G");a.addColumn({type:"string",role:"style"},
"Style < 4G");a.addColumn("number","Total > 4G");a.addColumn({type:"string",role:"style"},"Style > 4G");a.addColumn("number","Total unknown");a.addColumn({type:"string",role:"style"},"Style unknown");date_values=[];for(c=1;12>=c;c++)month=e.getMonth(),year=e.getFullYear(),date_to_add=new Date(year,month),d.push(date_to_add),date_values.push([date_to_add,b[c-1]["2G"],"color:gold",b[c-1]["4G"],"color:red",b[c-1]["8G"],"color:blue",b[c-1].unkn,"color:grey"]),e.setMonth(month-1);a.addRows(date_values);
return{data:a,options:{title:f,curveType:"function",isStacked:!1,hAxis:{title:"Months",ticks:d,format:"MMM"},vAxis:{title:"Num instances",viewWindow:{min:0},format:"#"},legend:{textStyle:{fontSize:10}},chartArea:{left:"5%",right:"10%"},focusTarget:"category",colors:["gold","red","blue","grey"],lineWidth:5,tooltip:{textStyle:{fontSize:10}},backgroundColor:"transparent"}}}
function build_data_per_month_flavours_mem(g,f){for(var b=[],d=["unkn","2G","4G","8G"],c=0;12>c;c++){b[c]={client_2G:0,client_4G:0,client_8G:0,client_unkn:0,server_2G:0,server_4G:0,server_8G:0,server_unkn:0,desktop_2G:0,desktop_4G:0,desktop_8G:0,desktop_unkn:0,other_2G:0,other_4G:0,other_8G:0,other_unkn:0};for(var e in d)if(g[d[e]][c])for(var a in g[d[e]][c])for(var h in g[d[e]][c][a])b[c][h+"_"+d[e]]+=g[d[e]][c][a][h]}d=[];e=new Date;a=new google.visualization.DataTable;a.addColumn({type:"date",
role:"domain"},"Date");a.addColumn("number","Total client < 2G");a.addColumn({type:"string",role:"style"},"Style client < 2G");a.addColumn("number","Total client < 4G");a.addColumn({type:"string",role:"style"},"Style client < 4G");a.addColumn("number","Total client > 4G");a.addColumn({type:"string",role:"style"},"Style client > 4G");a.addColumn("number","Total client > unknown");a.addColumn({type:"string",role:"style"},"Style client unknown");a.addColumn("number","Total server < 2G");a.addColumn({type:"string",
role:"style"},"Style server < 2G");a.addColumn("number","Total server < 4G");a.addColumn({type:"string",role:"style"},"Style server < 4G");a.addColumn("number","Total server > 4G");a.addColumn({type:"string",role:"style"},"Style server > 4G");a.addColumn("number","Total server unknown");a.addColumn({type:"string",role:"style"},"Style server unknown");a.addColumn("number","Total desktop < 2G");a.addColumn({type:"string",role:"style"},"Style desktop < 2G");a.addColumn("number","Total desktop < 4G");
a.addColumn({type:"string",role:"style"},"Style desktop < 4G");a.addColumn("number","Total desktop > 4G");a.addColumn({type:"string",role:"style"},"Style desktop > 4G");a.addColumn("number","Total desktop unknown");a.addColumn({type:"string",role:"style"},"Style desktop unknown");a.addColumn("number","Total other < 2G");a.addColumn({type:"string",role:"style"},"Style other < 2G");a.addColumn("number","Total other < 4G");a.addColumn({type:"string",role:"style"},"Style other < 4G");a.addColumn("number",
"Total other > 4G");a.addColumn({type:"string",role:"style"},"Style other > 4G");a.addColumn("number","Total other unknown");a.addColumn({type:"string",role:"style"},"Style other unknown");date_values=[];for(c=1;12>=c;c++)month=e.getMonth(),year=e.getFullYear(),date_to_add=new Date(year,month),d.push(date_to_add),date_values.push([date_to_add,b[c-1].client_2G,"color:darkgoldenrod",b[c-1].client_4G,"color:goldenrod",b[c-1].client_8G,"color:gold",b[c-1].client_unkn,"color:lightgrey",b[c-1].server_2G,
"color:darkviolet",b[c-1].server_4G,"color:deeppink",b[c-1].server_8G,"color:pink",b[c-1].server_unkn,"color:grey",b[c-1].desktop_2G,"color:slateblue",b[c-1].desktop_4G,"color:skyblue",b[c-1].desktop_8G,"color:blue",b[c-1].desktop_unkn,"color:darkgrey",b[c-1].other_2G,"color:teal",b[c-1].other_4G,"color:darkkhaki",b[c-1].other_8G,"color:green",b[c-1].other_unkn,"color:black"]),e.setMonth(month-1);a.addRows(date_values);return{data:a,options:{title:f,curveType:"function",isStacked:!1,hAxis:{title:"Months",
ticks:d,format:"MMM"},vAxis:{title:"Num instances",viewWindow:{min:0},format:"#"},legend:{textStyle:{fontSize:10}},chartArea:{left:"5%",right:"10%"},focusTarget:"category",colors:"darkgoldenrod goldenrod gold lightgrey darkviolet deeppink pink grey slateblue skyblue blue darkgrey teal darkkhaki green black".split(" "),lineWidth:5,tooltip:{textStyle:{fontSize:9}},backgroundColor:"transparent"}}}
function build_data_per_month_ltsp_usage(g,f){for(var b=[],d=0;36>d;d++){var c=Math.floor(d/3);g[d]&&(b[c]||(b[c]={0:0,1:0,unkn:0}),b[c][g[d][0]]=parseInt(g[d][1]))}c=[];var e=new Date,a=new google.visualization.DataTable;a.addColumn({type:"date",role:"domain"},"Date");a.addColumn("number","Total normal clients");a.addColumn({type:"string",role:"style"},"Total normal clients style");a.addColumn("number","Total ltsp clients");a.addColumn({type:"string",role:"style"},"Total ltsp clients style");a.addColumn("number",
"Total unknown clients");a.addColumn({type:"string",role:"style"},"Total unknown clients style");date_values=[];for(d=1;12>=d;d++)month=e.getMonth(),year=e.getFullYear(),date_to_add=new Date(year,month),c.push(date_to_add),date_values.push([date_to_add,b[d-1][0],"color:purple",b[d-1][1],"color:gold",b[d-1].unkn,"color:grey"]),e.setMonth(month-1);a.addRows(date_values);return{data:a,options:{title:f,curveType:"function",isStacked:!1,hAxis:{title:"Months",ticks:c,format:"MMM"},vAxis:{title:"Num instances",
viewWindow:{min:0},format:"#"},legend:{textStyle:{fontSize:10}},chartArea:{left:"5%",right:"10%"},focusTarget:"category",colors:["purple","gold","grey"],lineWidth:5,tooltip:{textStyle:{fontSize:10}},backgroundColor:"transparent"}}}
function build_data_per_month_ltsp_modes(g,f){for(var b=[],d=0;48>d;d++){var c=Math.floor(d/4);g[d]&&(b[c]||(b[c]={thin:0,semi:0,fat:0,unkn:0}),b[c][g[d][0]]=parseInt(g[d][1]))}c=[];var e=new Date,a=new google.visualization.DataTable;a.addColumn({type:"date",role:"domain"},"Date");a.addColumn("number","Total thin clients");a.addColumn({type:"string",role:"style"},"Total thin clients style");a.addColumn("number","Total semi clients");a.addColumn({type:"string",role:"style"},"Total semi clients style");
a.addColumn("number","Total fat clients");a.addColumn({type:"string",role:"style"},"Total fat clients style");a.addColumn("number","Total unknown clients");a.addColumn({type:"string",role:"style"},"Total unknown clients style");date_values=[];for(d=1;12>=d;d++)month=e.getMonth(),year=e.getFullYear(),date_to_add=new Date(year,month),c.push(date_to_add),date_values.push([date_to_add,b[d-1].thin,"color:purple",b[d-1].semi,"color:gold",b[d-1].fat,"color:olive",b[d-1].unkn,"color:grey"]),e.setMonth(month-
1);a.addRows(date_values);return{data:a,options:{title:f,curveType:"function",isStacked:!1,hAxis:{title:"Months",ticks:c,format:"MMM"},vAxis:{title:"Num instances",viewWindow:{min:0},format:"#"},legend:{textStyle:{fontSize:10}},chartArea:{left:"5%",right:"10%"},focusTarget:"category",colors:["purple","gold","olive","grey"],lineWidth:5,tooltip:{textStyle:{fontSize:10}},backgroundColor:"transparent"}}}
function build_data_per_month_releases_cpu(g,f){for(var b=[],d=["unkn","mono","dualquad","more"],c=0;12>c;c++){b[c]={"15_mono":0,"15_dualquad":0,"15_more":0,"15_unkn":0,"16_mono":0,"16_dualquad":0,"16_more":0,"16_unkn":0,"19_mono":0,"19_dualquad":0,"19_more":0,"19_unkn":0};for(var e in d)if(g[d[e]][c])for(var a in g[d[e]][c])for(var h in g[d[e]][c][a])b[c][a+"_"+d[e]]+=g[d[e]][c][a][h]}d=[];e=new Date;a=new google.visualization.DataTable;a.addColumn({type:"date",role:"domain"},"Date");a.addColumn("number",
"Total 15 mono processor");a.addColumn({type:"string",role:"style"},"Style 15 mono processor");a.addColumn("number","Total 15 dual or quad processor");a.addColumn({type:"string",role:"style"},"Style 15 dual or quad processor");a.addColumn("number","Total 15 more than quad processor");a.addColumn({type:"string",role:"style"},"Style 15 more than quad processor");a.addColumn("number","Total 15 unknown");a.addColumn({type:"string",role:"style"},"Style 15 unknown");a.addColumn("number","Total 16 mono processor");
a.addColumn({type:"string",role:"style"},"Style 16 mono processor");a.addColumn("number","Total 16 dual or quad processor");a.addColumn({type:"string",role:"style"},"Style 16 dual or quad processor");a.addColumn("number","Total 16 more than quad processor");a.addColumn({type:"string",role:"style"},"Style 16 more than quad processor");a.addColumn("number","Total 16 unknown");a.addColumn({type:"string",role:"style"},"Style 16 unknown");a.addColumn("number","Total 19 mono processor");a.addColumn({type:"string",
role:"style"},"Style 19 mono processor");a.addColumn("number","Total 19 dual or quad processor");a.addColumn({type:"string",role:"style"},"Style 19 dual or quad processor");a.addColumn("number","Total 19 more than quad processor");a.addColumn({type:"string",role:"style"},"Style 19 more than quad processor");a.addColumn("number","Total 19 unknown");a.addColumn({type:"string",role:"style"},"Style 19 unknown");date_values=[];for(c=1;12>=c;c++)month=e.getMonth(),year=e.getFullYear(),date_to_add=new Date(year,
month),d.push(date_to_add),date_values.push([date_to_add,b[c-1]["15_mono"],"color:darkgoldenrod",b[c-1]["15_dualquad"],"color:goldenrod",b[c-1]["15_more"],"color:gold",b[c-1]["15_unkn"],"color:lightgrey",b[c-1]["16_mono"],"color:darkviolet",b[c-1]["16_dualquad"],"color:deeppink",b[c-1]["16_more"],"color:pink",b[c-1]["16_unkn"],"color:darkgrey",b[c-1]["19_mono"],"color:palegreen",b[c-1]["19_dualquad"],"color:springgreen",b[c-1]["16_more"],"color:green",b[c-1]["16_unkn"],"color:darkseagreen"]),e.setMonth(month-
1);a.addRows(date_values);return{data:a,options:{title:f,curveType:"function",isStacked:!1,hAxis:{title:"Months",ticks:d,format:"MMM"},vAxis:{title:"Num instances",viewWindow:{min:0},format:"#"},legend:{textStyle:{fontSize:10}},chartArea:{left:"5%",right:"10%"},focusTarget:"category",colors:"darkgoldenrod goldenrod gold lightgrey darkviolet deeppink pink darkgrey palegreen springgreen green darkseagreen".split(" "),lineWidth:5,tooltip:{textStyle:{fontSize:10}},backgroundColor:"transparent"}}}
function build_data_per_month_cpu(g,f){for(var b=[],d=["unkn","mono","dualquad","more"],c=0;12>c;c++){b[c]={unkn:0,mono:0,dualquad:0,more:0};for(var e in d)if(g[d[e]][c])for(var a in g[d[e]][c])for(var h in g[d[e]][c][a])b[c][d[e]]+=g[d[e]][c][a][h]}d=[];e=new Date;a=new google.visualization.DataTable;a.addColumn({type:"date",role:"domain"},"Date");a.addColumn("number","Total mono processor");a.addColumn({type:"string",role:"style"},"Style mono processor");a.addColumn("number","Total dual or quad processor");
a.addColumn({type:"string",role:"style"},"Style dual or quad processor");a.addColumn("number","Total more than quad processor");a.addColumn({type:"string",role:"style"},"Style more than quad processor");a.addColumn("number","Total unknown");a.addColumn({type:"string",role:"style"},"Style unknown");date_values=[];for(c=1;12>=c;c++)month=e.getMonth(),year=e.getFullYear(),date_to_add=new Date(year,month),d.push(date_to_add),date_values.push([date_to_add,b[c-1].mono,"color:gold",b[c-1].dualquad,"color:red",
b[c-1].more,"color:blue",b[c-1].unkn,"color:grey"]),e.setMonth(month-1);a.addRows(date_values);return{data:a,options:{title:f,curveType:"function",isStacked:!1,hAxis:{title:"Months",ticks:d,format:"MMM"},vAxis:{title:"Num instances",viewWindow:{min:0},format:"#"},legend:{textStyle:{fontSize:10}},chartArea:{left:"5%",right:"10%"},focusTarget:"category",colors:["gold","red","blue","grey"],lineWidth:5,tooltip:{textStyle:{fontSize:10}},backgroundColor:"transparent"}}}
function build_data_per_month_flavours_cpu(g,f){for(var b=[],d=["unkn","mono","dualquad","more"],c=0;12>c;c++){b[c]={client_mono:0,client_dualquad:0,client_more:0,client_unkn:0,server_mono:0,server_dualquad:0,server_more:0,server_unkn:0,desktop_mono:0,desktop_dualquad:0,desktop_more:0,desktop_unkn:0,other_mono:0,other_dualquad:0,other_more:0,other_unkn:0};for(var e in d)if(g[d[e]][c])for(var a in g[d[e]][c])for(var h in g[d[e]][c][a])b[c][h+"_"+d[e]]+=g[d[e]][c][a][h]}d=[];e=new Date;a=new google.visualization.DataTable;
a.addColumn({type:"date",role:"domain"},"Date");a.addColumn("number","Total client mono processor");a.addColumn({type:"string",role:"style"},"Style client mono processor");a.addColumn("number","Total client dual or quad processor");a.addColumn({type:"string",role:"style"},"Style client dual or quad processor");a.addColumn("number","Total client more than quad processor");a.addColumn({type:"string",role:"style"},"Style client more than quad processor");a.addColumn("number","Total client unknown processor");
a.addColumn({type:"string",role:"style"},"Style client unknown processor");a.addColumn("number","Total server mono processor");a.addColumn({type:"string",role:"style"},"Style server mono processor");a.addColumn("number","Total server dual or quad processor");a.addColumn({type:"string",role:"style"},"Style server dual or quad processor");a.addColumn("number","Total server more than quad processor");a.addColumn({type:"string",role:"style"},"Style server more than quad processor");a.addColumn("number",
"Total server unknown processor");a.addColumn({type:"string",role:"style"},"Style server unknown processor");a.addColumn("number","Total desktop mono processor");a.addColumn({type:"string",role:"style"},"Style desktop mono processor");a.addColumn("number","Total desktop dual or quad processor");a.addColumn({type:"string",role:"style"},"Style desktop dual or quad processor");a.addColumn("number","Total desktop more than quad processor");a.addColumn({type:"string",role:"style"},"Style desktop more than quad processor");
a.addColumn("number","Total desktop unknown processor");a.addColumn({type:"string",role:"style"},"Style desktop unknown processor");a.addColumn("number","Total other mono processor");a.addColumn({type:"string",role:"style"},"Style other mono processor");a.addColumn("number","Total other dual or quad processor");a.addColumn({type:"string",role:"style"},"Style other dual or quad processor");a.addColumn("number","Total other more than quad processor");a.addColumn({type:"string",role:"style"},"Style other more than quad processor");
a.addColumn("number","Total other unknown processor");a.addColumn({type:"string",role:"style"},"Style other unknown processor");date_values=[];for(c=1;12>=c;c++)month=e.getMonth(),year=e.getFullYear(),date_to_add=new Date(year,month),d.push(date_to_add),date_values.push([date_to_add,b[c-1].client_mono,"color:darkgoldenrod",b[c-1].client_dualquad,"color:goldenrod",b[c-1].client_more,"color:gold",b[c-1].client_unkn,"color:lightgrey",b[c-1].server_mono,"color:darkviolet",b[c-1].server_dualquad,"color:deeppink",
b[c-1].server_more,"color:pink",b[c-1].server_unkn,"color:grey",b[c-1].desktop_mono,"color:slateblue",b[c-1].desktop_dualquad,"color:skyblue",b[c-1].desktop_more,"color:blue",b[c-1].desktop_unkn,"color:darkgrey",b[c-1].other_mono,"color:teal",b[c-1].other_dualquad,"color:darkkhaki",b[c-1].other_more,"color:green",b[c-1].other_unkn,"color:black"]),e.setMonth(month-1);a.addRows(date_values);return{data:a,options:{title:f,curveType:"function",isStacked:!1,hAxis:{title:"Months",ticks:d,format:"MMM"},
vAxis:{title:"Num instances",viewWindow:{min:0},format:"#"},legend:{textStyle:{fontSize:10}},chartArea:{left:"5%",right:"10%"},focusTarget:"category",colors:"darkgoldenrod goldenrod gold lightgrey darkviolet deeppink pink grey slateblue skyblue blue darkgrey teal darkkhaki green black".split(" "),lineWidth:5,tooltip:{textStyle:{fontSize:9}},backgroundColor:"transparent"}}}
function build_data_from_array(g,f){var b=[],d=new Date,c=new google.visualization.DataTable;c.addColumn({type:"date",role:"domain"},"Nhosts");c.addColumn("number",f);date_values=[];for(i=1;12>=i;i++)month=d.getMonth(),year=d.getFullYear(),date_to_add=new Date(year,month),b.push(date_to_add),date_values.push([date_to_add,g[i-1]]),d.setMonth(month-1);c.addRows(date_values);return{data:c,options:{title:f,curveType:"function",isStacked:!1,hAxis:{title:"Months",ticks:b,format:"MMM"},vAxis:{title:"Num hosts",
minValue:0,maxValue:"automatic",viewWindowMode:"pretty",viewWindow:{min:0,max:"auto"},format:"#"},legend:{textStyle:{fontSize:10}},chartArea:{left:"5%",right:"10%"},focusTarget:"category",lineWidth:5,tooltip:{textStyle:{fontSize:10}},backgroundColor:"transparent"}}}
function doExtendedChart(){end_load_time=get_time();var g=window.location.search.substr(1);""!=g&&(g="?"+g);var f={};start_get_time=get_time();$("#accordion").append('<div id="loading"></div>');start_graph_time=end_get_time=0;$.ajax({datatype:"json",url:"./GetExtendedStats"+g,success:function(b){b=JSON.parse(b);start_graph_time=end_get_time=get_time();var d=null,c={machines_per_month:{},clients_per_month:{},freq_updates_per_month:{},change_releases:{},change_flavours:{},count_ltsp:{},count_mode:{},
architectures:{},mem:{},cpu:{}},e;for(e in b){if("clients"==e)for(var a in c)if(b[e][a])switch(a){case "machines_per_month":f.clients_per_month||(f.clients_per_month={});f.clients_per_month.hosts||(f.clients_per_month.hosts={});f.clients_per_month.title="Machines";f.clients_per_month.hosts.graph=build_data_from_array(b[e][a],"Number of unique machines used");f.clients_per_month.hosts.title="Number of unique machines used";break;case "clients_per_month":f.clients_per_month||(f.clients_per_month={});
f.clients_per_month.releases||(f.clients_per_month.releases={});f.clients_per_month.flavours||(f.clients_per_month.flavours={});f[a].title="Machines";f[a].releases.graph=build_data_per_month_releases(b[e][a],"Number instances by release per month");f[a].releases.title="Number instances by release per month";f[a].flavours.graph=build_data_per_month_flavours(b[e][a],"Number instances by flavour per month");f[a].flavours.title="Number instances by flavour per month";break;case "freq_updates_per_month":f.changes||
(f.changes={},f.changes.title="Upgrades");f.changes.updates||(f.changes.updates={});f.changes.updates.graph=build_data_from_array(b[e][a],"Number updates per month");f.changes.updates.title="Number updates per month";break;case "change_releases":f.changes||(f.changes={},f.changes.title="Upgrades");f.changes.releases||(f.changes.releases={});f.changes.releases.graph=build_data_from_array(b[e][a],"Change releases per month");f.changes.releases.title="Change releases per month";break;case "change_flavours":f.changes||
(f.changes={},f.changes.title="Changes");f.changes.flavours||(f.changes.flavours={});f.changes.flavours.graph=build_data_from_array(b[e][a],"Change flavours per month");f.changes.flavours.title="Change flavours per month";break;case "architectures":f[a]||(f[a]={global:{},releases:{},flavours:{}},f[a].title="Architectures");f[a].global.graph=build_data_per_month_arch(b[e][a],"Architectures per month");f[a].global.title="Architectures distribution per month";f[a].releases.graph=build_data_per_month_release_arch(b[e][a],
"Architectures by release per month");f[a].releases.title="Architectures distribution by release per month";f[a].flavours.graph=build_data_per_month_flavour_arch(b[e][a],"Architectures by flavour per month");f[a].flavours.title="Architectures distribution by flavour per month";break;case "mem":f[a]||(f[a]={global:{},releases:{},flavours:{}},f[a].title="Memory");f[a].global.graph=build_data_per_month_mem(b[e][a],"Memory per month");f[a].global.title="Memory distribution per month";f[a].releases.graph=
build_data_per_month_releases_mem(b[e][a],"Memory by release per month");f[a].releases.title="Memory distribution by release per month";f[a].flavours.graph=build_data_per_month_flavours_mem(b[e][a],"Memory by flavour per month");f[a].flavours.title="Memory distribution by flavour per month";break;case "cpu":f.cpu||(f.cpu={global:{},releases:{},flavours:{}},f.cpu.title="CpuS");f.cpu.global.graph=build_data_per_month_cpu(b[e][a],"Number CpuS per month");f.cpu.global.title="Number CpuS distribution per month";
f.cpu.releases.graph=build_data_per_month_releases_cpu(b[e][a],"Number CpuS by release per month");f.cpu.releases.title="Number CpuS distribution by release per month";f.cpu.flavours.graph=build_data_per_month_flavours_cpu(b[e][a],"Number CpuS by release per month");f.cpu.flavours.title="Number CpuS distribution by flavour per month";break;case "count_ltsp":case "count_mode":f.ltsp||(f.ltsp={},f.ltsp.title="LTSP Usage"),"count_ltsp"!=a||f.ltsp.usage||(f.ltsp.usage={},f.ltsp.usage.graph=build_data_per_month_ltsp_usage(b[e][a],
"LTSP usage per month"),f.ltsp.usage.title="LTSP Use"),"count_mode"!=a||f.ltsp.modes||(f.ltsp.modes={},f.ltsp.modes.graph=build_data_per_month_ltsp_modes(b[e][a],"LTSP type by type per month"),f.ltsp.modes.title="Clients LTSP Mode")}if("apps"==e)for(var g in b.apps)if(b.apps[g].app&&b.apps[g].app_use){d=b.apps[g].app;var m="usage_"+g;f[m]={};f[m].title="Application usage "+d;f[m].releases={};f[m].releases.graph=build_data_per_month_releases(b[e][g].app_use,"Application use by release per month ("+
d+")");f[m].releases.title="Use per month for application "+d;f[m].flavours={};f[m].flavours.graph=build_data_per_month_flavours(b[e][g].app_use,"Application use by flavour per month ("+d+")");f[m].flavours.title="Use per month for application "+d}e.startsWith("debug")&&("debug_query_time"==e&&(query_time=b[e]),"debug_keep_alive"==e&&(keep_alive=b[e]))}for(var l in f)if(f[l].title){$("#accordion").append('<h3 class="'+l+'">'+f[l].title+'</h3><div id="'+l+'"></div>');for(var n in f[l])"title"!=n&&
f[l][n].graph&&($("#"+l).append("<div id="+l+"_"+n+"></div>"),b=get_sizes(l),f[l][n].graph.options.width=b.width,f[l][n].graph.options.height=b.height,(new google.visualization.LineChart(document.getElementById(l+"_"+n))).draw(f[l][n].graph.data,f[l][n].graph.options))}$("#loading").remove();$("#accordion").accordion({active:!1,collapsible:!0,heightStyle:"content",autoHeight:!1});null!=d&&$(".app_use").click();end_graph_time=get_time();print_stats(end_graph_time,query_time);run_css_fixes()},async:!0})}
function run_css_fixes(){$("#accordion>div>div:last-child svg").css("height",String(1.1*Number($("#accordion>div>div:last-child svg").css("height").slice(0,-2)))+"px")}function param_to_obj(g){"?"==g.substr(0,1)&&(g=g.substr(1));if(""==g)return"Undefined";var f={};g.split("&").forEach(function(b){b=b.split("=");f[b[0]]=decodeURIComponent(b[1])});return f}
function doChart(g){g=void 0===g?"":g;var f=window.location.search.substr(1),b=3;""!=f&&(f="?"+f,params=param_to_obj(f),params.hasOwnProperty("init")&&params.hasOwnProperty("window")?b=1:f="");end_load_time=get_time();start_get_time=get_time();$("#accordion").append('<div id="loading"></div>');""==g?(url="./GetStats"+f,limit=10):(url="./GetLliurexStats"+f,limit=1E3);$.getJSON(url,function(d){start_graph_time=end_get_time=get_time();count=0;for(key in d)if(!key.startsWith("debug"))for(key2 in d[key])count++;
max_graph=count*b;obj=[];var c,e;for(distro in d)"debug_init_range"==distro&&(c=d[distro]),"debug_end_range"==distro&&(e=d[distro]),"debug_query_time"==distro&&(query_time=d[distro]),"debug_keep_alive"==distro&&(keep_alive=d[distro]);for(distro in d)if(!distro.startsWith("debug"))for(sabor in d[distro])for(titles=1==b?["Top apps from "+c+" until "+e]:["Top apps este mes","Top apps ultimo mes","Top apps penultimo mes"],divname="chart_"+distro+"_"+sabor,$("#accordion").append("<h3>Distro "+distro+"("+
sabor+")</h3>"),$("#accordion").append('<div class="'+divname+'"></h3>'),i=0;i<b;i++){$("div."+divname).append('<div id="'+divname+i+'"></div>');k=0;var a=new google.visualization.DataTable;a.addColumn("string","App");a.addColumn("number","Count");for($.each(d[distro][sabor][i][0],function(b,c){a.addRow([b,parseInt(c)]);k++});10>k;)a.addRow(["",0]),k++;obj.push(a);titles[i]=titles[i]+" (Total clients: "+d[distro][sabor][i][1].nclients+")";drawChart(obj[obj.length-1],titles[i],divname+i,k)}end_graph_time=
get_time();print_stats(end_graph_time,query_time)})}num_ready=0;function ready_charts(){num_ready++;num_ready==max_graph&&($("#accordion>#loading").remove(),$("#accordion").accordion({active:!1,collapsible:!0,heightStyle:"content",autoHeight:!1}),run_css_fixes())}
function print_stats(g,f){g=void 0===g?0:g;f=void 0===f?0:f;$("#stats_box").append('<span class="stats">Load time: '+((end_load_time-start_load_time)/1E3).toString()+" sec</span>");$("#stats_box").append('<span class="stats">Get time: '+parseFloat((end_get_time-start_get_time)/1E3-f).toFixed(3).toString()+" sec</span>");$("#stats_box").append('<span class="stats">Graph time: '+((g-start_graph_time)/1E3).toString()+" sec</span>");$("#stats_box").append('<span class="stats">Query time: '+parseFloat(f).toFixed(3).toString()+
" sec</span>");$("#stats_box").append('<span class="stats">Updated: '+keep_alive.toString()+"</span>")}function get_time(){return Date.now?Date.now():(new Date).getTime()}var start_graph_time=0,end_graph_time=0,start_load_time=get_time(),end_load_time=0,start_get_time=0,end_get_time=0,query_time="",keep_alive="";