var stats={},graphs={},charts={},timeout=10,minutes=10,max_items=6*minutes,parent="#chart_div",show={load:{title:"Carga",group:!1},mem_used:{title:"Memoria usada",group:!1},queues:{group:!0,title:"Queues",members:{queue_desktop:{title:"Desktops",group:!1},queue_other:{title:"Others",group:!1},queue_server:{title:"Servers",group:!1},queue_client:{title:"Clients",group:!1}}},select_window:{title:"Select Window",group:!1},temp_sizes:{group:!0,title:"Temp sizes",members:{temp_packages_size:{title:"Packages",
group:!1},temp_clients_size:{title:"Clients",group:!1}}},db_sizes:{group:!0,title:"DB sizes",members:{db_clients_size:{title:"Clients",group:!1},db_packages_size:{title:"Packages",group:!1}}},processing_at:{title:"SpeedUp",group:!1},paused:{title:"Pausa",group:!1}},cfg={watched:{},groups:{},divs:{}};
function get_cfg(a,c){for(var b in a)try{a[b].group?(cfg.groups[b]={title:a[b].title,members:{}},cfg.divs[b]={title:a[b].title},get_cfg(a[b].members,b)):(cfg.watched[b]={title:a[b].title},c?cfg.groups[c].members[b]={title:a[b].title}:cfg.divs[b]={title:a[b].title})}catch(d){}}get_cfg(show);
function get_data(a){$.getJSON("./SystemStats",function(c){for(var b in c)if(b in cfg.watched||"keepalive"==b){var d=c[b];b in stats?(stats[b].length>max_items-1&&stats[b].splice(0,1),stats[b].push(d)):stats[b]=[d]}a&&a()})}function show_data(a){$("#accordion").empty();var c="",b;for(b in stats){var d=b+" = ";for(var e in stats[b])c+=d+stats[b][e],d=", ";c+="\n"}$("#accordion").append("<pre>"+c+"</pre>");a&&a()}function init_system_stats(){initialize()}
function loop(){for(var a=0;a<arguments.length;a++)f=arguments[a],f(),window.setTimeout(function(){loop(f)},1E3*timeout)}var initialized=!1;function initialize(){if(initialized)return!0;initialized=!0;get_data(make_divs);loop(function(){get_data(function(){init_google_data();gen_google_data();$("#loading").remove();view_google_graphs()})})}function make_divs(a){$(parent).empty();for(var c in cfg.divs)$(parent).append($('<div id="chart_'+c+'"> </div>'));a&&a()}
function timestamp_to_string(a){var c=new Date(1E3*a);a=c.getHours();var b=c.getMinutes();c=c.getSeconds();10>a&&(a="0"+a.toString());10>b&&(b="0"+b.toString());10>c&&(c="0"+c.toString());return a+":"+b+":"+c}function get_current_divs(){var a={};$(parent+">div").each(function(){a[this.id.substring(6)]={}});return a}
function init_google_data(a){for(var c in get_current_divs())if(graphs[c]=new google.visualization.DataTable,graphs[c].addColumn("string","Time"),c in cfg.watched)graphs[c].addColumn("number",cfg.watched[c].title);else for(var b in cfg.groups[c].members)graphs[c].addColumn("number",cfg.groups[c].members[b].title);a&&a()}
function gen_google_data(a){for(var c in get_current_divs())if(c in cfg.groups)graphs[c].addRows(make_google_array(stats.keepalive,cfg.groups[c].members));else{var b={};b[c]={};graphs[c].addRows(make_google_array(stats.keepalive,b))}a&&a()}function make_google_array(a,c){for(var b=[],d=0;d<a.length;d++){var e=[timestamp_to_string(Number(a[d]))],g;for(g in c)e.push(Number(stats[g][d]));b.push(e)}return b}
function view_google_graphs(){var a=0,c;for(c in cfg.divs)a+=1;a={title:"",height:(window.innerHeight-10)/a,legend:!0,backgroundColor:"transparent",chartArea:{left:75,width:window.innerWidth-275},fontSize:10,hAxis:{textPosition:"none"},vAxis:{viewWindow:{min:0}}};for(var b in graphs)b in cfg.groups&&(a.isStacked="absolute"),a.title=cfg.divs[b].title,charts[b]=new google.visualization.AreaChart(document.getElementById("chart_"+b)),charts[b].draw(graphs[b],a)};
